name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - developer
      - release
  pull_request:
    branches:
      - main
      - developer
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # Instalação de dependências
      - name: Install dependencies
        run: npm install

      # Lint do código
      - name: Run Lint
        run: npm run lint

      # Build do projeto
      - name: Build project
        run: npm run build

      # Deploy para Vercel
      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./
          vercel-project-name: 'portfolio'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          